import {
  Home, UtensilsCrossed, ReceiptText, BarChart3, MoreHorizontal, Bell, BellOff, BellRing,
  Sun, Moon, Languages, LogOut, Plus, Pencil, Trash2, Printer, X, ChevronLeft, ChevronRight,
  ChefHat, QrCode, Tags, Armchair, Gift, Users, UserCog, Settings, Search, Check, Download,
  Upload, Volume2, Play, Store, Coffee, Star, Phone, MapPin, Image as ImageIcon, Camera,
  GripVertical, User, Circle, ShoppingCart, Hand, Sparkles, Boxes, Wallet, Clock, Eye, EyeOff,
  Mail, TrendingUp, Repeat, Award, CalendarClock,
  Ticket, CalendarDays, ScanLine, PartyPopper, Cake, Calendar, CheckCircle2, XCircle, MapPin as Map2,
  Flame, ClipboardList, LayoutGrid, List as ListIcon, Heart, Copy,
  Flag, Car, ShoppingBag, AlertTriangle,
  Mic, Paperclip, Square, Undo, FileText,
  Wrench, MessageCircle, Scale, KeyRound, FolderOpen, ArrowUpDown, ArrowLeftRight, Lock, Minus, Wifi, CreditCard,
  Zap, ArrowUp, NotepadText, Briefcase, Theater, PenLine, Package, ChartColumnBig,
  Palette, Layers, Type as TypeIcon, Shapes, Pause, RotateCw, Share, SquarePlus,
} from 'lucide-react'

const MAP = {
  home: Home,
  menu: UtensilsCrossed,
  cashier: ReceiptText,
  reports: BarChart3,
  more: MoreHorizontal,
  bell: Bell,
  bellOff: BellOff,
  bellRing: BellRing,
  sun: Sun,
  moon: Moon,
  lang: Languages,
  logout: LogOut,
  add: Plus,
  edit: Pencil,
  copy: Copy,
  delete: Trash2,
  print: Printer,
  close: X,
  back: ChevronLeft,
  next: ChevronRight,
  kitchen: ChefHat,
  qr: QrCode,
  categories: Tags,
  tables: Armchair,
  offers: Gift,
  customers: Users,
  staff: UserCog,
  settings: Settings,
  search: Search,
  check: Check,
  lock: Lock,
  card: CreditCard,
  receipt: ReceiptText,
  minus: Minus,
  wifi: Wifi,
  download: Download,
  upload: Upload,
  sound: Volume2,
  play: Play,
  store: Store,
  coffee: Coffee,
  star: Star,
  phone: Phone,
  pin: MapPin,
  image: ImageIcon,
  camera: Camera,
  drag: GripVertical,
  user: User,
  cart: ShoppingCart,
  waiter: Hand,
  sparkles: Sparkles,
  inventory: Boxes,
  wallet: Wallet,
  clock: Clock,
  palette: Palette,
  layers: Layers,
  text: TypeIcon,
  shapes: Shapes,
  pause: Pause,
  reload: RotateCw,
  share: Share,
  addToHome: SquarePlus,
  eye: Eye,
  eyeOff: EyeOff,
  mail: Mail,
  trending: TrendingUp,
  repeat: Repeat,
  award: Award,
  peak: CalendarClock,
  events: PartyPopper,
  ticket: Ticket,
  reservations: CalendarDays,
  scan: ScanLine,
  cake: Cake,
  calendar: Calendar,
  ok: CheckCircle2,
  no: XCircle,
  flame: Flame,
  orders: ClipboardList,
  grid: LayoutGrid,
  list: ListIcon,
  heart: Heart,
  complaint: Flag,
  car: Car,
  bag: ShoppingBag,
  warning: AlertTriangle,
  mic: Mic,
  clip: Paperclip,
  stop: Square,
  undo: Undo,
  file: FileText,
  wrench: Wrench,
  message: MessageCircle,
  scale: Scale,
  key: KeyRound,
  folder: FolderOpen,
  arrowUpDown: ArrowUpDown,
  arrowLeftRight: ArrowLeftRight,
  zap: Zap,
  arrowUp: ArrowUp,
  notepad: NotepadText,
  briefcase: Briefcase,
  theater: Theater,
  penLine: PenLine,
  package: Package,
  chartBar: ChartColumnBig,
}

// Usage: <Icon name="home" size={20} />
export default function Icon({ name, size = 20, strokeWidth = 2, ...rest }) {
  const C = MAP[name] || Circle
  return <C size={size} strokeWidth={strokeWidth} {...rest} />
}
